microsoft/CEDAR.Core.Collector

README.md
Also added validation build badges at the top.
=> Initial ReadMe.

Core.Collectors/Collector/CollectionNode.cs
This is the first step in renaming that property.
=> Deprecating old API

Core.Collectors/Context/FunctionContext.cs, Core.Collectors/Context/FunctionContextWriter.cs, Core.Collectors/IO/RecordWriterCore.cs
Also move, context-related writing functionality to the function context writer.
=> Add SliceDate to FunctionContext

Core.Collectors/Collector/CollectorBase.cs, Core.Collectors/Config/ConfigManager.cs, Core.Collectors/Config/StorageManager.cs, Core.Collectors/IO/AdlsBulkRecordWriter.cs, Core.Collectors/IO/AzureBlobRecordWriter.cs, Core.Collectors/IO/RecordWriterCore.cs
Also do minor clean-up on preparing deprecating "outputPathPrefix".
=> Extend StorageManager with ADO-related settings to prepare for ADO changes.

Core.Collectors/Config/StorageManager.cs, Core.Collectors/IO/AdlsBulkRecordWriter.cs
This is needed to be able to deploy different versions as well as potential roots to different products.
=> Extract out the root folder and version value to the config

Core.Collectors.Tests/Cache/InmemoryCache.cs, Core.Collectors.Tests/IO/InMemoryRecordWriter.cs, Core.Collectors/Cache/AzureTableCache.cs, Core.Collectors/Cache/ICache.cs, Core.Collectors/IO/AzureHelpers.cs, Core.Collectors/IO/IRecordWriter.cs, Core.Collectors/IO/RecordWriterCore.cs, Core.Collectors/IO/SplitAzureBlobRecordWriter.cs
Improvements mainly needed by the RecordOutputService.
* ICache.CacheAtomicAsync(..) => ensures that an update on a cache is done atomically.
* IRecordWriter.WriteLineAsync(..) => ability to output string content (rather than a JObject).
* AzureHelpers.ListStorageQueuesAsync(..) => ability to list storage queues in a given storage account.
=> New utility functions

Core.Collectors/IO/RecordWriterCore.cs
This bug mainly affects the ADLSBulkUploadWriter and RecordOutputService since it requires the recordWriter to be re-used even when NotifyCurrentOutputAsync(..) throws an exception. Currently, RecordWriterService is the only place where this happens.
Rough timeline that triggers the bug:
- RecordWriterService calls NewOutputAsync(..) to Flush the data.
- NewOutputAsync(..) fails since NotifyCurrentOutputAsync(..) throws an exception (e.g., the notorious "cannot move the file exception")
- With the previous behavior, at this point, this.currentWriter in RecordWriterCore is disposed, however, RecrodWriterService handles the exception and keeps (re-)using the recordWriter (hence this.currentWriter.
- Future calls on currentWriter (e.g., WriteLineAsync(..)) throws "ObjectDisposedException" …
=> Let RecordWriterCore re-use when NotifyCurrentOutputAsync throws

Core.Collectors/Telemetry/ApplicationInsightsTelemetryClient.cs
Required by some security changes.
=> Obfuscate request identity if the ID is a GUID.

Core.Collectors/Context/FunctionContext.cs
Just as a place holder for now, will be filled in later.
=> Add dequeue count to FunctionContext.

Core.Collectors/Web/HttpResponseSignature.cs
Rather than only the response message.
=> Extend HttpResponseSignature to match based on the response object

Core.Collectors/Utility/AsyncTaskExecutor.cs
Adds the ability to execute tasks in parallel (for tasks that are void)
=> AsyncTaskExecutor

Core.Collectors/Utility/AsyncTaskExecutor.cs
Also add capability to force waiting for completion.
=> Add capability to run tasks that return values to AsyncTaskExecutor

Core.Collectors/Core.Collectors.csproj
Addressing a security vulnerability causing pipeline failures.
=> Upgrade System.Text.Encodings.Web to 4.5.1

.deployment/CEDAR.AzureDevOps.Collector.yml
replace build configuration variable for DotNet tests.
=> Update CEDAR.AzureDevOps.Collector.yml for Azure Pipelines

Core.Collectors/Collector/CollectorBase.cs, Core.Collectors/Collector/IBatchingHttpRequest.cs, Core.Collectors/Web/HttpExceptionSignature.cs, Core.Collectors/Web/HttpResponseSignature.cs, Core.Collectors/Web/IAllowListStatus.cs, Core.Collectors/Web/RequestResult.cs
=> Allow List Handling

Core.Collectors.Tests/Web/FixedHttpClient.cs
allow unique responses from FixedHttpClient for post requests with unique bodies
=> AllowList QueryLimitExeeded for WorkItemCollector

.deployment/CEDAR.GitHub.Collector.yml
Update endpoint (service connection) to new service connection created by Kivanc.
=> Update CEDAR.GitHub.Collector.yml for Azure Pipelines

Core.Collectors/Collector/CollectorBase.cs, Core.Collectors/Web/HttpExceptionSignature.cs, Core.Collectors/Web/HttpResponseSignature.cs, Core.Collectors/Web/IAllowListStatus.cs, Core.Collectors/Web/RequestResult.cs
Provide RequestMessage parameter to allowlist handler function
=> Provide RequestMessage parameter to allowlist handler functions

Core.Collectors/Web/HttpExceptionSignature.cs
this will break tests, buddy PR incoming
=> Move and unify http exception signatures

Core.Telemetry/OpenTelemetryHelpers.cs, Core.Telemetry/OpenTelemetryTrace.cs
Add new Trace type for ConfigurationLoad
=> added new activity type for ConfigurationLoad

Core.Collectors.Tests/Utility/MockDateTime.cs, Core.Collectors/Web/RateLimiter.cs
=> IDateTime abstraction for RateLimiter
