microsoft/CEDAR.Core.Collector

Core.Collectors/Collector/IWebRequestStatsTracker.cs
This is one of the changes to bring StatsTracker from AzureDevOps collectos so that it can be also used with the GitHub collectors and becomes part of the core library.
=> Introduce IWebRequestStatsTracker

Core.Collectors.Tests/IO/InMemoryRecordWriter.cs, Core.Collectors/Collector/StatsTracker.cs, Core.Collectors/IO/IRecordStatsTracker.cs, Core.Collectors/IO/IRecordWriter.cs
Moving StatsTracker from ADO collectors to Core so that both can benefit from it. Also changing ADOHttpWebClient with IWebRequestStatsTracker so that it does not refer anything ADO-specific. Finally adds documentation on what StatsTracker is and how to use it.
=> Introduce StatsTracker

Core.Collectors/Collector/CollectorBase.cs
The loop detection ignores the very first response as an optimization (in case there is no batching, we don't want to waste computation power). However, this caused a bug when the second request of the batching yields to empty result since the default value of the previous response matches empty response.
This was a valid case for ADO collectors with the CommitChanges API. This change fixes this behavior by assigning the initial value of the previous response to something invalid so that the second response can never cause the loop detection to fail.
=> Fix loop detection when the response for the second request is empty

Core.Collectors/Collector/CollectorBase.cs
Loop detection state is not cleared between two different batching HTTP requests and therefore, there was a corner case, where if two different HTTP requests result with the exact response and they have multiple batches, this would be detected as a loop and the function would be terminated per loop detection logic. At high-level the following needs to happen to trigger this bug:
* a web request e.g., REQUEST1 has a response with multiple pages. Assume 2 pages and the second page content would be X
* Another web request REQUEST2 also has a response with 2 pages and the second page content would be X.
All in all, when we are evaluation loop detection for REQUEST2's second page, we would detect a loop (although none happened so far) and terminate the function.
This commit resets the state …
=> Fix loop detection bug when different API requests result with the same response

Core.Collectors/Context/FunctionContextWriter.cs
So that GitHub WebhookProcessorContextWriter can properly extend this. Keeping the old one since the update will be compatibility-breaking for ADO and GitHub collectors (will be removed once those are changed first).
=> Add generic version of FunctionContextWriter.

Core.Collectors/Context/FunctionContextWriter.cs
This is no longer needed. Just cleaning up.
=> Remove non-generic FunctionContextWriter

Core.Collectors/Web/RetryRule.cs
This is needed to make flakey web exception retries more efficient and intelligent. Especially when one type of exception (e.g., BadGateway) happens more frequently than the others.
=> Add ability to track and consume attempt index within the retry rule.

Core.Collectors/Config/StorageManager.cs, Core.Collectors/IO/IRecordWriter.cs, Core.Collectors/IO/RecordWriterNotificationMessage.cs, Core.Collectors/IO/SplitAzureBlobRecordWriter.cs
Introduces an Azure Blob record writer that automatically splits each record type to its own file. This kind of split is needed to ease the transtion to RecordWriterService that will be coming next.
The implementation is largely based on the existing AzureBlobRecordWriter but is done separately due to two reasons:
1. Once this is rolled out and switched with the existing AzureBlobRecordWriter, we will deprecate the existing AzureBlobRecordWriter.
2. Adding "split" capability to RecordWriteCore<T> makes the abstraction pretty complex and is not needed since there are no plans to add similar functionality to ADLS bulk record writer, at least in the short/medium term.
=> Introduce SplitAzureBlobRecordWriter

Core.Collectors/IO/RecordWriterCore.cs, Core.Collectors/IO/SplitAzureBlobRecordWriter.cs
This is already the behavior with WriteRecordAsync.
=> Initialize record writer if WriteLineAsync is the first call.

Core.Collectors/IO/AdlsBulkRecordWriter.cs
There is a good chance that the error was happening because some of the destination's parents were missing due to day overlap (with 10 minutes addition).
=> Fix File.Move(..) bug.

Core.Collectors.Tests/Config/ConfigManagerTests.cs, Core.Collectors/Config/ConfigManager.cs
This commit moves the API domain from local.settings.json to Settings.json. To do so, I added two methods to the ConfigManager (GetApiDomainToken() and GetApiDomain()). In the setup of ConfigManager I created a map from the DefaultKey to the ApiDomainToken. I also increased coverage in ConfigManagerTests.
This pull request contains changes to files referenced in my pull request under the same name in CEDAR.GitHub.Collector.
=> Move ApiDomain to global section of the config (CEDAR.GitHub.Collector Issue #36)

Core.Collectors.Tests/Config/ConfigManagerTests.cs, Core.Collectors/Config/ConfigManager.cs
Currently, apiDomainToken and GetApiDomain() are in ConfigManager. This logic is only relevant to GithubConfigManager, so I moved the code pertaining the API domain out of this class. To access certain variables/methods in the child class I changed them to protected.
=> Move apiDomainToken and GetApiDomain() from parent to child class

Core.Collectors.Tests/Config/MockConfigValueResolver.cs
This is needed for some changes on the ADO side.
=> Add capability to have dictionary-based configs in the mock config value resolver

Core.Collectors/Collector/CustomQueueProcessor.cs, Core.Collectors/Core.Collectors.csproj
Changes for Issue #40. Adds a CustomQueueProcessor (allows for infinite time to live for queue messages) to CEDAR/Core as it is used in both CEDAR/GitHub and ADO.
=> Add CustomQueueProcessor

Core.Collectors/IO/RecordWriterCore.cs, Core.Collectors/IO/SplitAzureBlobRecordWriter.cs
These two lines are causing approx. 0.4M trace events per day. They happen so frequently and are valid when e.g., there is no data generated during collection that there is no gain from logging them. Removing to save some cost.
=> Reduce logging

Core.Collectors/Utility/JTokenUtility.cs, Core.Collectors/Web/AdlsClientWrapper.cs
This PR moves the ADLS ingestion application details from local.settings.json to Settings.json. 
To do this, I pass the global settings JSON string to AdlsClientWrapper and parse it for two new keys `AdlsIngestionApplicationId` and `AdlsIngestionApplicationSecretEnvironmentVariable`. The former is moved directly from local settings, the latter contains the environment variable name of the ADLS secret. The global settings string is accessed from builder services (changes in `ServiceStartup.Configure()` in CEDAR/GitHub and ADO will be made to add the string to builder services).
I also added a utility class `JTokenUtility` that allows me to perform checks on JTokens just like `string.IsNullOrEmpty()` and `string.IsNullOrWhiteSpace()`. This is great because it cleans up the checks in …
=> Move ADLS ingestion app details from local to global settings

Core.Collectors/Cache/AzureTableCache.cs
This will help us cache CloudTable initialization so that we don't need to keep calling CreateIfNotExistsAsync call.
=> Add a new constructor to AzureTableCache.

Core.Collectors/IO/AzureHelpers.cs, Core.Collectors/IO/SplitAzureBlobRecordWriter.cs
Add ability to cached cloud queue initializations in AzureHelpers. This is especially important to optimize queue client instantiations for AzureSplitBlobWriter
=> CachedCloudQueues

Core.Collectors/IO/AdlsBulkRecordWriter.cs, Core.Collectors/IO/RecordWriterCore.cs
DisposeInternal does not work since the latest upload happens after dispose (after the file is closed). Therefore, move the logic to delete local root to FinalizeAsync(..) which is where the last upload is happening.
=> Fix ADLS Bulk Record Writer

Core.Collectors.Tests/IO/InMemoryRecordWriter.cs, Core.Collectors/IO/AdlsBulkRecordWriter.cs, Core.Collectors/IO/AzureBlobRecordWriter.cs, Core.Collectors/IO/IRecordWriter.cs, Core.Collectors/IO/RecordWriterCore.cs, Core.Collectors/IO/SplitAzureBlobRecordWriter.cs
Not having a map from blob files to ADLS is making some of the debugging more difficult. This change introduces that mapping.
=> Maintain a file map in ADLS bulk upload.

Core.Collectors.Tests/Web/FixedHttpClient.cs, Core.Collectors/Web/HttpClientWrapper.cs, Core.Telemetry/AggregateTelemetryClient.cs, Core.Telemetry/ApplicationInsightsTelemetryClient.cs, Core.Telemetry/OpenTelemetryTelemetryClient.cs, Core.Telemetry/OpenTelemetryTracer.cs
implements ITelemetryClient and emits OpenTelemetry events as Spans.
implements ITelemetryClient, constructed of multiple ITelemetryClient objects and emits telemetry to each. This will be used to Aggregate ApplicationInsight and OpenTelemetry telemetry clients during migration to Genva.
remove trace from http requests as these will be tracked through telemetry.
remove logging from telemetry client, this behavior is redundant with modern telemetry.
add `GetActivity(string name)` to allow OpenTelemetryTelemetryClient to create custom named Spans.
=> Introduce new OpenTelemetryTelemetryClient and AggregateTelemetryClient

Core.Collectors/Collector/CachingCollector.cs
This is needed to fix an issue in the WorkItem collector where we cache the same collection multiple times.
=> Make it possible to process and cache multiple collection nodes.

Core.Telemetry/OpenTelemetryHelpers.cs
Addtional default tag on metrics and traces `SiteName` which allows for improved dashboard integration.
=> Added SiteName to default telemetry tags

Core.Collectors.Tests/Collector/CollectorTests.cs, Core.Collectors/Collector/CollectionNode.cs, Core.Collectors/Collector/CollectorBase.cs
This lambda extends the functionality to process a record (a row of the response) with the response itself (in case we need to refer something from the response). Needed for an upcoming change in CG processing.
=> Introduce ProcessRecordWithResponseAsync.

Core.Collectors/Cache/RateLimitTableEntity.cs, Core.Collectors/Web/RateLimiter.cs
This is useful to improve Azure DevOps rate limiter. Also fix the way internal caching for rate limiting details are done.
=> Capture ResponseCode in RateLimiter cache.

Core.Collectors/IO/AdlsBulkRecordWriter.cs, Core.Collectors/IO/RecordWriterCore.cs
When ROS (ADLS Bulk upload writer) starts uploads very close to each other (within the same second), the final ADLS path becomes the same as the previous upload and therefore the data gets overwritten. This results in data loss.
This change appends a serial number (upload index) at the end of the file names to ensure that the file paths are always unique for a given ADLS Bulk Record Writer (ROS) instance.
=> Fix ROS timestamp bug
